/* GENERATED BY JTRENT238 MOD MAKER */

package com.jtrent238.modmaker.mod.dicemaker.dice_side_blank;


import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.util.StatCollector;

public class dice_side_blank extends Block{

	public dice_side_blank(Material p_i45394_1_) {
		super(p_i45394_1_);
	}

}
